/** Asset paths under /public/nav */
export const NAV_ASSETS = {
  logo: "/nav/logo.png",
  logoIcon: "/nav/logo-icon.png",
  sparkle: "/nav/sparkle.png",
  chevronDown: "/nav/chevron-down.png",
  dexlessLogo: "/nav/dexless-logo.png",
  more: "/nav/more.png",
  rwd: "/nav/rwd.png",
  language: "/nav/language.png",
  personal: "/nav/personal.png",
  arbitrum: "/nav/arbitrum.png",
  walletChevron: "/nav/wallet-chevron.svg",
  menuPerps: "/nav/menu-perps.png",
  menuSwap: "/nav/menu-swap.png",
  menuDocs: "/nav/menu-docs.png",
  chevronRight: "/nav/chevron-right.png",
  externalLink: "/nav/external-link.png",
  menu: "/nav/menu-hamburger.png",
  menuClose: "/nav/menu-close.png",
  menuTradeDna: "/nav/menu-trade-dna.png",
  menuAi: "/nav/menu-ai.png",
  menuTrading: "/nav/menu-trading.png",
  menuMarkets: "/nav/menu-markets.png",
  menuPortfolio: "/nav/menu-portfolio.png",
  menuReferrals: "/nav/menu-referrals.png",
  menuPoints: "/nav/menu-points.png",
  menuVaults: "/nav/menu-vaults.png",
  menuMoreDots: "/nav/menu-more-dots.png",
  menuSupport: "/nav/menu-support.png",
  menuSwapAccount: "/nav/menu-swap-account.png",
  menuAccount: "/nav/menu-account.png",
  bnTrading: "/nav/bn-trading.png",
  bnTradingActive: "/nav/bn-trading-active.png",
  bnPortfolio: "/nav/bn-portfolio.png",
  bnPortfolioActive: "/nav/bn-portfolio-active.png",
  bnMarkets: "/nav/bn-markets.png",
  bnMarketsActive: "/nav/bn-markets-active.png",
  bnReferrals: "/nav/bn-referrals.png",
  bnReferralsActive: "/nav/bn-referrals-active.png",
  bnAi: "/nav/bn-ai.png",
  bnAiActive: "/nav/bn-ai-active.png",
} as const;

/** Footer assets under /public/footer */
export const FOOTER_ASSETS = {
  twitter: "/footer/twitter.png",
  orderly: "/footer/orderly.png",
} as const;
